### ISSUE TITLE
Garfanzo panics a lot.

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/altctrl#46]
Soooooo I don't know how to write a CLI.

Friendly reminder to me (once you've got the Serde stuff figured out with the WindowContent enum and have documented a bit more) to FIX ALL THESE DAMN PANICS.

**Comment by WillNilges** [comment]
#47 might help with this.

**Comment by nicholastmosher** [comment]
@WillNilges take a look at this file from back when I was writing the CLI for Flipper. Basically, you can use clap to parse any string, that string doesn't necessarily have to come from command-line arguments, it can come from stdin instead. So you can build a clap::app structure with the parsing options you want, then feed it input from a REPL-style reader. In Flipper's case I used a crate called rustyline.

* https://github.com/nicholastmosher/flipper/blob/the_rustening/console/src/bin/modules_cli.rs
* https://github.com/nicholastmosher/flipper/blob/the_rustening/console/src/bin/main.rs

**Comment by WillNilges** [comment]
groovy. I'll have a look!

**Comment by WillNilges** [comment]
Closed. Not really important anymore.
